version: "3.9"
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: evently
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  geodb:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: evently_geo
    volumes:
      - geodb_data:/var/lib/postgresql/data
    ports:
      - "5436:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: ./src/Api
    depends_on:
      db:
        condition: service_healthy
      geo:
        condition: service_started
    environment:
      - ConnectionStrings__Default=Host=db;Port=5432;Database=evently;Username=postgres;Password=postgres
      - ASPNETCORE_ENVIRONMENT=Development
      - Jwt__Key=supersecret_dev_jwt_key_change_me
      - Jwt__Issuer=MekanBudur
      - Jwt__Audience=MekanBudurUsers
      - ASPNETCORE_URLS=http://+:8080
      - GeoService__BaseUrl=http://geo:8080
    ports:
      - "8084:8080"
    healthcheck:
      test: ["CMD-SHELL", "exit 0"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s


  geo:
    build: ./src/Geo
    depends_on:
      geodb:
        condition: service_healthy
    environment:
      - ConnectionStrings__Default=Host=geodb;Port=5432;Database=evently_geo;Username=postgres;Password=postgres
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - CORS__AllowedOrigins=*
    ports:
      - "8083:8080"
    healthcheck:
      test: ["CMD-SHELL", "exit 0"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  pgadmin:
    image: dpage/pgadmin4:latest
    depends_on:
      - db
      - geodb
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mekanbudur.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "5051:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    healthcheck:
      test: ["CMD-SHELL", "exit 0"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

volumes:
  db_data:
  geodb_data:
  pgadmin_data:
